service: serverless-bolt-js
frameworkVersion: "3"
useDotenv: true
provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  timeout: 30
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
functions:
  slack:
    handler: dist/app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-esbuild
  - serverless-offline
